### ISSUE TITLE
xAPI Agent Profile Resource - error in order of elements

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#1109]
**Version**
2.1.3 and 2.1.4 (but guessing this is a global issue)

**Steps to reproduce the bug**
1. Submit an agentProfile with the agent.name first and agent.mbox second (in the JSON object)
```
    "agent" : {
        "objectType" : "Agent", 
        "name" : "User Full Name", 
        "mbox" : "mailto:support@example.com"
    },
```
2. Attempt to retrieve the agentProfile value

**Expected behaviour**
Value of the agentProfile will be returned

**Actual behaviour**
404 response. agentProfile doesn't exist.

**Additional information**
OS: CentOS 7.4
Browser: Chrome (latest)

If you swap the order of agent.mbox and agent.name, it is retrievable:
```
    "agent" : {
        "objectType" : "Agent", 
        "mbox" : "mailto:support@example.com",
        "name" : "User Full Name"
    },
```

**Comment by ryansmith94** [comment]
Hmmm this is also odd because it shouldn't be storing the name I don't think.

**Comment by ryansmith94** [comment]
Okay we are storing the name and I can't think why we're doing that, we certainly shouldn't be using it to match an agent as far as I'm aware.

**Comment by davidpesce** [comment]
If you want me to take a look at attempting a PR, can you point me to where I should be looking.? I haven't dug too deep into the architecture of llv2 yet.

**Comment by ryansmith94** [comment]
It's all good @davidpesce, I'm on it already, thanks for the offer though 👍

**Comment by davidpesce** [comment]
The spec doesn't say it's invalid if you do include both. It does say that you can only use one of the four reverse functional identifiers (mbox, mbox_sha1sum, openid, or account), but name is listed as an optional.

**Comment by ryansmith94** [comment]
Yeah that's fine. I don't think we should have been storing the name in the database, it's not actually required. Just waiting for the build to pass over in learninglocker/xapi-agents#43 then I'll get this fix released 👍

**Comment by davidpesce** [comment]
You da man! Thanks, Ryan!

**Comment by ryansmith94** [comment]
Haha you're welcome @davidpesce 👍 that's just gone live [v2.1.9 of the xapi-service](https://github.com/LearningLocker/xapi-service/releases/tag/v2.1.9) - got to love automated releases haha.

**Comment by ryansmith94** [comment]
Hey @davidpesce you need to `yarn install && yarn build` 😄

**Comment by davidpesce** [comment]
Yeah, that's what I forgot. The docs still show "npm install" and "npm run build". I did that and it worked like a charm!

**Comment by ryansmith94** [comment]
Ah cool yeah npm will work too just a little less safe than yarn if you're not using npm 5 (our AMIs and deploy scripts still install npm 3 because we've not tested the webapp with npm 5). The difference is that npm 3 doesn't use the `package-lock.json` file whereas npm 5 does. Yarn uses the `yarn.lock` file. Not sure if you're familiar with lock files, just ensures that you install the exact same version of dependencies as our tests.

**Comment by davidpesce** [comment]
Ok, cool. I wonder if it's worth it to update the custom install docs? http://docs.learninglocker.net/guides-custom-installation/

**Comment by ryansmith94** [comment]
Yeah it almost certainly is. If you're able to make a PR there that would be awesome. It should be the [src/guides-custom-installation.md](https://github.com/LearningLocker/docs/blob/master/src/guides-custom-installation.md) file that needs updating in the docs repo.

**Comment by davidpesce** [comment]
Yup can do!

**Comment by davidpesce** [comment]
Confirming that this definitely resolved the issue. To make doubly-sure, I also tried re-migrating the LLv1 agentProfiles into the LLv2 DB and my course was able to retrieve them without a hitch. It also didn't create new agentProfiles (the originals retrieved fine).

**Comment by ryansmith94** [comment]
Brilliant cheers @davidpesce 👍 

Awesome thank you for confirming! That's really good.
