### ISSUE TITLE
Actor and Activity APIs return errors

### ISSUE THREAD

**Issue by paulnebel** [LearningLocker/learninglocker#503]
I've been querying the Actor and Activity APIs for my instance of Learning Locker and seem to be getting back some unexpected errors.

I though at first that I'd constructed the queries incorrectly, but I've studied the spec and I've also looked at how a test tool provided by ADL works and I have confirmed that I'm not making any mistakes.  As a final test I set up a free Rustici Scorm Cloud account so that I could compare what I get back from that to what I get back from Learning Locker.  Here are the results (rest assured that the actor and activity IDs I'm using exist in the respective systems - I'm not looking for something that isn't there!):

* Agent API
 * Rustici Scorm Cloud
     * request: {my Scorm Cloud Endpoint}/agents?agent={"name":"Joe Bloggs","mbox":"mailto:joe@bloggs.com","objectType":"Agent"}
     * response: {"name":["Joe Bloggs"],"mbox":["mailto:joe@bloggs.com"],"objectType":"Person"} - ***CORRECT***
 * Learning Locker
     * request: {my Learning Locker Endpoint}/agents?agent={"name":"Joe Bloggs","mbox":"mailto:joe@bloggs.com","objectType":"Agent"}
     * response: 
{
error: true
message: "Required parameter is missing - profileId"
code: 500
trace: "#0 /var/www/learninglocker/app/controllers/xapi/DocumentController.php(30): Controllers\xAPI\DocumentController->checkParams(Array, Array, Array) #1 
.... (more stack trace)
} - ***INCORRECT***  *This does not conform to the xAPI spec.  There is no requirement for a profileId parameter to be associated with this xAPI request.  Besides that, this shouldn't be returning a 500 error!*

* Activity API
 * Scorm Cloud
    * request: {my Scorm Cloud Endpoint}/activities?activityId=http://www.example.com/tincan/activities/eeXHsQaH
    * response: {"id":"http://www.example.com/tincan/activities/eeXHsQaH","definition":{"name":{"en-US":"Example Activity"},"description":{"en-US":"Example activity definition"}},"objectType":"Activity"}} - ***CORRECT***
 * Learning Locker
    * request: {my Learning Locker Endpoint}/activities?activityId=http://www.example.com/tincan/activities/LrNRxzxE
    * response: 
{
error: true
message: "key() expects parameter 1 to be array, null given"
code: 500
trace: "#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'key() expects p...', '/var/www/learni...', 40, Array) #1 
.... (more stack trace)
} - ***INCORRECT*** *This does not conform to the xAPI spec.  The activityId parameter does not need to be an array according to the xAPI specification.  Making it an array simply returns a different error.  Besides that, this shouldn't be returning a 500 error!*

Is this a bug in Learning Locker?

**Comment by ryansmith94** [comment]
Thanks for reporting the issues. Both should be fixed in `issue/tidyup` however that branch is currently unusable. Will let you know when it's usable.

**Comment by ht2** [comment]
Hi Paul, 

Thanks for submitting the issue. I also received an email from Mark about this and I've been in dialogue with Ryan about the situation. We are currently at a place where we have fixed these particular issues as part of a larger drive to refactor our code in the issues/tidyup branch. As we move forward its looking more and more likely that issues/tidup will end up being a 2.0 release of Learning Locker. This obviously has ramifications on conformance fixes that have been made in this branch, as they wouldn't get applied into a 1.x release. As such I have asked Ryan to apply the conformance fixes that have occurred as part of the tidy up, back into the main develop branch. I'm hoping we will be able to push these fixes out (starting with this issue) within the next few days. I'll keep you posted.

James

**Comment by ryansmith94** [comment]
This has now been fixed in the `develop` branch.

**Comment by paulnebel** [comment]
Hi James

Thanks for your response.  I have to say that I'm concerned that two such
obvious errors have made it into your official stable release.  This is on
the back of another error in the previous stable release whereby the GET to
/data/xAPI/statements with statementId returned a code 500.  To me, this is
the third endpoint that should be tested.  The first would be to create a
statement, then to retrieve all statements and then to retrieve statements
by ID.  This leads me to ask what your unit testing strategy is.  Can you
tell me how many unit tests you have, show me the test coverage and output
from the latest release and tell me how this fits into your deployment
strategy?  As an example, our code automatically executes more than 1000
unit tests on a Jenkins CI server before being deployed by that server.
Deployment only takes place if all tests are passed and test output is
immediately available.  Of course, this doesn't guarantee that no errors
will make it through into the final release but it does ensure that any
changes we have made to the codebase have not broken anything that was
already working.  Following deployment we run a full Quality Assurance test
by hand to ensure that as few errors as possible make it into the final
release.  Do you have a similar strategy?  If so, does this test all the
endpoints of the xAPI and if not, why not?  Please forgive my apparent
bluntness but I need to understand the answer to these questions in order
to say that we support xAPI in our product using Learning Locker - if I
can't say with some certainty that Learning Locker supports xAPI then I
can't say that our product supports xAPI.

Regards

Paul



On 10 February 2015 at 16:01, James Mullaney <notifications@github.com>
wrote:

> Hi Paul,
>
> Thanks for submitting the issue. I also received an email from Mark about
> this and I've been in dialogue with Ryan about the situation. We are
> currently at a place where we have fixed these particular issues as part of
> a larger drive to refactor our code in the issues/tidyup branch. As we move
> forward its looking more and more likely that issues/tidup will end up
> being a 2.0 release of Learning Locker. This obviously has ramifications on
> conformance fixes that have been made in this branch, as they wouldn't get
> applied into a 1.x release. As such I have asked Ryan to apply the
> conformance fixes that have occurred as part of the tidy up, back into the
> main develop branch. I'm hoping we will be able to push these fixes out
> (starting with this issue) within the next few days. I'll keep you posted.
>
> James
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LearningLocker/learninglocker/issues/503#issuecomment-73725341>
> .
>



-- 
*Paul Nebel*
Senior Mobile Architect

*g**o**m**o*

63-65 North Wharf Road  London  W2 1LA  United Kingdom
*DDI *+4420 32382837  *Switchboard* +44 207 402 1554
*gomolearning.com <http://gomolearning.com>*

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the sender.  Please
note that any views or opinions presented in this email are solely those of
the author and do not necessarily represent those of Gomo Learning.  Gomo
Learning accepts no liability for any damage caused by any virus
transmitted by this email and therefore you should check this email and any
attachments for the presence of viruses.

Gomo Learning Ltd. Registered in England under Company Number: 4131113.
Registered Office: 52 Old Steine, Brighton, East Sussex, BN1 1NH, UK

**Comment by ryansmith94** [comment]
Hi Paul, thank you for your request for information. As you can see in the readme, we use Travis for our continuous integration, this integration builds the current commit and tests it against our tests. In future we hope to also include the ADL test suite in this integration.

Having said that, we do also run our forked version of the ADL test suite which has over 4000 tests each containing around 5 assertions each. I run each release through all of the available tests before releasing a new version of Learning Locker.

Due to the complexity and size of the xAPI specification, there are holes in the tests, however, the testing for this specification is always improving and with your help reporting issues such as this one the situation will continue to improve.

Apologies for any inconvenience these issues have caused you.

**Comment by paulnebel** [comment]
Hi

Can you give me any idea when this fix will make it to a release?  I've
updated to version 1.3.4 today and I'm still getting these issues, along
with blank Reporting and Exporting pages.  We're due to go live in 3 weeks
with xAPI support via Learning Locker and I don't seem to have a fully
working version yet.

Thanks

Paul

On 11 February 2015 at 11:29, Ryan Smith <notifications@github.com> wrote:

> This has now been fixed in the develop branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LearningLocker/learninglocker/issues/503#issuecomment-73867310>
> .
>



-- 
*Paul Nebel*
Senior Mobile Architect

*g**o**m**o*

63-65 North Wharf Road  London  W2 1LA  United Kingdom
*DDI *+4420 32382837  *Switchboard* +44 207 402 1554
*gomolearning.com <http://gomolearning.com>*

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the sender.  Please
note that any views or opinions presented in this email are solely those of
the author and do not necessarily represent those of Gomo Learning.  Gomo
Learning accepts no liability for any damage caused by any virus
transmitted by this email and therefore you should check this email and any
attachments for the presence of viruses.

Gomo Learning Ltd. Registered in England under Company Number: 4131113.
Registered Office: 52 Old Steine, Brighton, East Sussex, BN1 1NH, UK

**Comment by ryansmith94** [comment]
The fixes were included in 1.3.3 as detailed in the [release notes](https://github.com/LearningLocker/learninglocker/releases).

Sounds like you haven't ran `composer install` and the migrations detailed in the [release notes](https://github.com/LearningLocker/learninglocker/releases).
