### ISSUE TITLE
Text overflowing

### ISSUE THREAD

**Issue by stephenlane** [LearningLocker/learninglocker#596]
**Version**
latest at 1.3.9

**Steps to reproduce the bug**
Have long urls as acitivites

**Expected behaviour**
Should potentially wrap or truncate to make fit

**Actual behaviour**
Text overflows boundary

**Server information**
nginx and mongodb

**Client information**
OS: ubuntu
Browser: chrome version 1.0.1

![image](https://cloud.githubusercontent.com/assets/4368495/7272298/9bc65650-e8e1-11e4-92a6-689584a61503.png)

**Comment by ryansmith94** [comment]
Hi @stephenlane, thanks for reporting this issue and using our template. Thanks for the screenshot, that really helped us to understand your problem :+1: I'll try to update this for either 1.3.10, 1.3.11, or 1.4.0 depending on the priority of other issues and enhancements.

**Comment by stephenlane** [comment]
Hi @ryansmith94  thats great to hear :) look forward to the fix

**Comment by ryansmith94** [comment]
Hi @stephenlane, this is wrapped for me on Chrome 41.0.2272.118 m. Could you please confirm that your Chrome version is 1.0.1?

![image](https://cloud.githubusercontent.com/assets/3045513/7294790/526232fa-e9a8-11e4-8fbe-5194c8faf54d.png)

**Comment by stephenlane** [comment]
Hi @ryansmith94  screen shot of browser version 

![image](https://cloud.githubusercontent.com/assets/4368495/7294910/403d7e30-e9a9-11e4-9d01-6a1ffbe80185.png)

**Comment by ryansmith94** [comment]
Hi @sanduhrs, thanks again for reporting this issue and following our guidelines. This has now been reproduced and fixed. The fix has been merged into the [develop branch](https://github.com/LearningLocker/learninglocker/tree/develop). This should be released with version 1.3.10.

**Comment by stephenlane** [comment]
Thats great to hear. Thanks @ryansmith94

**Comment by ryansmith94** [comment]
You're welcome @stephenlane :+1:

**Comment by stephenlane** [comment]
@ryansmith94 just upgaded to the latest version and this is still an issue. I did skip the last release as I didn't have time to upgrade

**Comment by ryansmith94** [comment]
Hi @stephenlane can you please try reloading without your cache? This is definitely fixed for me as shown in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/3045513/7533764/3145486c-f56c-11e4-8450-c64c2798cfff.png)

**Comment by stephenlane** [comment]
@ryansmith94 I always forget to clear my cache ;) cheers

**Comment by ryansmith94** [comment]
@stephenlane no worries :+1:
